require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OriginsController do

  # This should return the minimal set of attributes required to create a valid
  # Origin. As you add validations to Origin, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "address" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OriginsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all origins as @origins" do
      origin = Origin.create! valid_attributes
      get :index, {}, valid_session
      assigns(:origins).should eq([origin])
    end
  end

  describe "GET show" do
    it "assigns the requested origin as @origin" do
      origin = Origin.create! valid_attributes
      get :show, {:id => origin.to_param}, valid_session
      assigns(:origin).should eq(origin)
    end
  end

  describe "GET new" do
    it "assigns a new origin as @origin" do
      get :new, {}, valid_session
      assigns(:origin).should be_a_new(Origin)
    end
  end

  describe "GET edit" do
    it "assigns the requested origin as @origin" do
      origin = Origin.create! valid_attributes
      get :edit, {:id => origin.to_param}, valid_session
      assigns(:origin).should eq(origin)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Origin" do
        expect {
          post :create, {:origin => valid_attributes}, valid_session
        }.to change(Origin, :count).by(1)
      end

      it "assigns a newly created origin as @origin" do
        post :create, {:origin => valid_attributes}, valid_session
        assigns(:origin).should be_a(Origin)
        assigns(:origin).should be_persisted
      end

      it "redirects to the created origin" do
        post :create, {:origin => valid_attributes}, valid_session
        response.should redirect_to(Origin.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved origin as @origin" do
        # Trigger the behavior that occurs when invalid params are submitted
        Origin.any_instance.stub(:save).and_return(false)
        post :create, {:origin => { "address" => "invalid value" }}, valid_session
        assigns(:origin).should be_a_new(Origin)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Origin.any_instance.stub(:save).and_return(false)
        post :create, {:origin => { "address" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested origin" do
        origin = Origin.create! valid_attributes
        # Assuming there are no other origins in the database, this
        # specifies that the Origin created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Origin.any_instance.should_receive(:update).with({ "address" => "MyString" })
        put :update, {:id => origin.to_param, :origin => { "address" => "MyString" }}, valid_session
      end

      it "assigns the requested origin as @origin" do
        origin = Origin.create! valid_attributes
        put :update, {:id => origin.to_param, :origin => valid_attributes}, valid_session
        assigns(:origin).should eq(origin)
      end

      it "redirects to the origin" do
        origin = Origin.create! valid_attributes
        put :update, {:id => origin.to_param, :origin => valid_attributes}, valid_session
        response.should redirect_to(origin)
      end
    end

    describe "with invalid params" do
      it "assigns the origin as @origin" do
        origin = Origin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Origin.any_instance.stub(:save).and_return(false)
        put :update, {:id => origin.to_param, :origin => { "address" => "invalid value" }}, valid_session
        assigns(:origin).should eq(origin)
      end

      it "re-renders the 'edit' template" do
        origin = Origin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Origin.any_instance.stub(:save).and_return(false)
        put :update, {:id => origin.to_param, :origin => { "address" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested origin" do
      origin = Origin.create! valid_attributes
      expect {
        delete :destroy, {:id => origin.to_param}, valid_session
      }.to change(Origin, :count).by(-1)
    end

    it "redirects to the origins list" do
      origin = Origin.create! valid_attributes
      delete :destroy, {:id => origin.to_param}, valid_session
      response.should redirect_to(origins_url)
    end
  end

end
